### ISSUE TITLE
Performance?

### ISSUE THREAD

**Issue by mikhail-sytchev** [t27duck/active_reporting#11]
What about performance? I mean, you are using OLTP database (Postgres) for OLAP queries. The key value of this gem is to change developer's mindset first to treat reports functionality as a set of reporting best practices? Or it's aimed to increase reports render speed?

**Comment by t27duck** [comment]
I'd say it's more about the former. You'd in theory get some small speed boost due to the gem not instantiating active record objects and instead returning basic hashes generated from more targeted queries.

**Comment by mikhail-sytchev** [comment]
thnx
