### ISSUE TITLE
Possibly incorrect code example in wiki

### ISSUE THREAD

**Issue by joshforbes** [t27duck/active_reporting#27]
Hello :wave:

This library is really great. We are thinking about using it for a live analytics dashboard at work. Thanks for all the work you have put into it.

While going through the docs I think I found an out of date example in the wiki

https://github.com/t27duck/active_reporting/wiki/Configuring-Dimension-Information
![image](https://user-images.githubusercontent.com/3682518/61906737-fca0d800-aef9-11e9-8e76-73285233e372.png)

I don't think `hierarchy_labels` exist anymore: https://github.com/t27duck/active_reporting/commit/399ebe91526e2bda4137bc209f2ee8f3d4b42ab6

Unfortunately since I am just getting up to speed on the gem I am not yet sure what it should be changed to. But I thought I would at least point it out.  Thanks!

**Comment by t27duck** [comment]
Wiki page updated. Thank you for pointing that out.
