### ISSUE TITLE
[FAQ] has_many relationships do not work 

### ISSUE THREAD

**Issue by kirantpatil** [t27duck/active_reporting#6]
Hi,

You made changes to README file 4 months ago.

Does has_many relationships still not supported ?

Thanks.

**Comment by t27duck** [comment]
That is correct. The nature of ROLAP commonly does not work with has_many relationships. There's not really much one can do to "support" a one to many relationship for reporting.

The only real option would be to implement, on the database side, what is called a "bridge table" or an "intermediate table". There are many examples and tutorials regarding this pattern for BI / ROLAP.

**Comment by kirantpatil** [comment]
Thanks.
